---

- name: Ping
  hosts: all

  tasks:
  - name: ping
    win_ping:
  - name: Copy folder contents recursively
    win_copy:
      src: /var/lib/jenkins/archive/MyFirstJob.git
      dest: C:\Users\Administrator\Documents\
  - name: Execute git clone command
    win_command: git clone C:\Users\Administrator\Documents\MyFirstJob.git
