---

- name: Ping
  hosts: all

  tasks:
  - name: ping
    win_ping:
  - name: Copy folder contents recursively
    win_copy:
      src: /var/lib/jenkins/archive/MyFirstJob.git
      dest: C:\Users\Administrator\Documents\
  - name: Run command on windows
    win_shell: git clone C:\Users\Administrator\Documents\MyFirstJob.git
    args:
      executable: cmd
    register: homedir_out
